### ISSUE TITLE
updating code to gurobi 10.0.2

### ISSUE THREAD

**Issue by Krarilotus** [saref/frustration-index-XOR#2]
Hello,
i tried out to work with the provided code, but unfortunately i couldn'tget hold of the older gurobi solver implementation. Now python spits out some errors, where you set the attributes, as it can only handle 2 arguments: attribute name and the new value:

def setAttr(self,
            attrname: str,
            newvalue: Any) -> None
            
Will this code be updated for future reference? Or is there also a gurobi free version out there somewhere, that could be used instead to cut off one of the dependancies?

Greetings
Johannes

**Comment by saref** [comment]
Hello Johannes,

I just ran the Jupyter notebook with gurobi 10.0.2 on my system and it executed successfully without producing any errors. I am not sure why you get that error on your system. 

>Or is there also a gurobi free version out there somewhere
Gurobi is a commercial solver, but the Gurobi website offers a free academic license for non-commercial purposes by users affiliated with academic institutions. Please check the readme file for the detailed instructions on requesting such a license: https://github.com/saref/frustration-index-XOR#readme
You can alternatively check the readme of my newer repo which covers the same steps for first-time users of Gurobi, but with more recent links and details:
https://github.com/saref/bayan#gurobi-installation-with-free-academic-license

>that could be used instead to cut off one of the dependancies?
This notebook depends on Gurobi because it was the most powerful solver that I had access to at the time. You may consider coding the XOR integer programming model from https://doi.org/10.1002/net.21907 yourself to solve it with a different solver.

This is the output I got from running the code with Gurobi 10.0.2 today (for a random G(n,m) graph):

> Set parameter TimeLimit to value 36000
> Set parameter Threads to value 4
> Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)
> 
> CPU model: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, instruction set [SSE2|AVX]
> Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
> 
> Optimize a model with 46 rows, 30 columns and 136 nonzeros
> Model fingerprint: 0x6e3d416a
> Variable types: 0 continuous, 30 integer (30 binary)
> Coefficient statistics:
>   Matrix range     [1e+00, 1e+00]
>   Objective range  [1e+00, 1e+00]
>   Bounds range     [1e+00, 1e+00]
>   RHS range        [1e+00, 1e+00]
> Found heuristic solution: objective 10.0000000
> Found heuristic solution: objective 8.0000000
> Presolve removed 10 rows and 5 columns
> Presolve time: 0.00s
> Presolved: 36 rows, 25 columns, 105 nonzeros
> Extracted 5 lazy constraints
> Found heuristic solution: objective 7.0000000
> Variable types: 0 continuous, 25 integer (25 binary)
> Found heuristic solution: objective 4.0000000
> 
> Root relaxation: objective 2.500000e+00, 13 iterations, 0.00 seconds (0.00 work units)
> 
>     Nodes    |    Current Node    |     Objective Bounds      |     Work
>  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
> 
>      0     0 infeasible    0         4.00000    4.00000  0.00%     -    0s
> 
> Explored 1 nodes (20 simplex iterations) in 0.05 seconds (0.00 work units)
> Thread count was 4 (of 4 available processors)
> 
> Solution count 4: 4 7 8 10 
> 
> Optimal solution found (tolerance 1.00e-04)
> Best objective 4.000000000000e+00, best bound 4.000000000000e+00, gap 0.0000%
> Instance 0  solution equals 4.0
> 
>    EXPERIMENT STATS   
> 
> Frustration indices: [4.0]
> Average frustrarion index 4.0
> 
> Solve times: [0.07]
> Average solve time 0.06696391105651855
> 
> Effective branching factors (EBFs) [1.0]
> Average EBF 1.0

**Comment by Krarilotus** [comment]
I think it must have to do with me newly installing python on this PC. As i have now version 3.11 it might have to do with other dependancies. I ll look into it and keep you updated.

Thank you for the quick reply! It must be on my end then!

**Comment by Krarilotus** [comment]
I've debugged my code, and it seems to just run fine. I guess, it is just the debugger thats spitting out the errors for not providing sufficient arguments for the setAtrr function, because it doesn't find the 3 argument function that is inherited somehow.

Sorry for bothering you. The code runs fine and all is good! Thank you for the help!
